### ISSUE TITLE
packer not waiting for IP ip_wait_timeout not respected

### ISSUE THREAD

**Issue by SylvainMartel** [hashicorp/packer-plugin-vsphere#126] opened 2021-11-04 18:49 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Hi, when trying to build a linux VM, packer won't wait for the machine to get an IP and destroy the VM while it is still installing the OS(I am using kickstarter and a slightly modified version of this(wonderful) repo ahttps://github.com/rainpole/packer-vsphere for the code)

I have looked at other similar issues about this, but no solutions from those to my problem.

If I run with the `-debug` flag, and let the OS installation finish before allowing the "Waiting for IP" step, all works fine.  Packer gets the IP, so it doesn't look like a communication issue.  But without the  `-debug` flag it will fail after waiting for about 2m30s even though the  ip_wait_timeout  is set at 20m.

I have included only the end of the logs for brevity

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `1.7.8`

### Log Fragments and crash.log files
2021/11/04 11:03:54 packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe plugin: 2021/11/04 11:03:54 Sending char 'g', code CodeG, shift false
2021/11/04 11:03:54 packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe plugin: 2021/11/04 11:03:54 Special code '<enter>' found, replacing with: CodeReturnEnter
2021/11/04 11:03:54 packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe plugin: 2021/11/04 11:03:54 [INFO] Waiting 1s
2021/11/04 11:03:55 packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe plugin: 2021/11/04 11:03:55 Special code '<leftctrl>' found, replacing with: CodeLeftControl
2021/11/04 11:03:55 packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe plugin: 2021/11/04 11:03:55 Sending char 'x', code CodeX, shift false
2021/11/04 11:03:55 packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe plugin: 2021/11/04 11:03:55 Special code '<leftctrl>' found, replacing with: CodeLeftControl
2021/11/04 11:03:56 packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe plugin: 2021/11/04 11:03:56 [INFO] Waiting for IP, up to total timeout: 20m0s, settle timeout: 5s
2021/11/04 11:03:56 ui: ==> vsphere-iso.linux-redhat-linux: Waiting for IP...
2021/11/04 11:05:58 ui: ==> vsphere-iso.linux-redhat-linux: Power off VM...
2021/11/04 11:05:58 ui: ==> vsphere-iso.linux-redhat-linux: Destroying VM...
2021/11/04 11:05:59 [INFO] (telemetry) ending vsphere-iso.linux-redhat-linux
2021/11/04 11:05:59 ui error: Build 'vsphere-iso.linux-redhat-linux' errored after 2 minutes 31 seconds: Post "https://10.205.120.2/sdk": EOF
2021/11/04 11:05:59 ui: 
==> Wait completed after 2 minutes 31 seconds
2021/11/04 11:05:59 machine readable: error-count []string{"1"}
2021/11/04 11:05:59 ui error: 
==> Some builds didn't complete successfully and had errors:
2021/11/04 11:05:59 machine readable: vsphere-iso.linux-redhat-linux,error []string{"Post \"https://10.205.120.2/sdk\": EOF"}
2021/11/04 11:05:59 ui error: --> vsphere-iso.linux-redhat-linux: Post "https://10.205.120.2/sdk": EOF
2021/11/04 11:05:59 ui: 
==> Builds finished but no artifacts were created.
2021/11/04 11:05:59 [INFO] (telemetry) Finalizing.
2021/11/04 11:06:00 waiting for all plugin processes to complete...
2021/11/04 11:06:00 C:\Users\sma084\AppData\Roaming\packer.d\plugins\github.com\hashicorp\vsphere\packer-plugin-vsphere_v1.0.2_x5.0_windows_amd64.exe: plugin process exited
2021/11/04 11:06:00 C:\Data\tools\packer.exe: plugin process exited

**Comment by tenthirtyam** [comment] 2021-11-04 18:58
Thanks for the compliment on the project. :)

Are you using the http or disk common data source? Which OSI?

Ryan
@tenthirtyam

**Comment by kinwolfqc** [comment] 2021-11-04 19:02
Hi, the OS is RHEL7 indeed. 
I am using the default http data source
```

// Boot and Provisioning Settings
common_data_source      = "http"
common_http_ip          = null
common_http_port_min    = 8000
common_http_port_max    = 8099
common_ip_wait_timeout  = "20m"
common_shutdown_timeout = "15m"
```

**Comment by tenthirtyam** [comment] 2021-11-04 19:02
If you are using the default http datasource in the project, can you confirm that the machine image being built can communicate back to the host which is running Packer to the IP and port for which it binds?

You can also toggle the common data source to "disk" to run out "http" as the issue.

Ryan

**Comment by kinwolfqc** [comment] 2021-11-04 19:10
> If you are using the default "http" datasource in the project, can you confirm that the machine image being built can communicate back to the host which is running Packer to the IP and port for which it binds?

Well, if I run with -debug and wait for the VM to finish installing before allowing the step "waiting for ip"  to run, it can see the IP of the vm, so the communication seems good .  
 
```
==> vsphere-iso.linux-redhat-linux: Set boot order...
==> vsphere-iso.linux-redhat-linux: Power on VM...
==> vsphere-iso.linux-redhat-linux: Pausing after run of step 'StepRun'. Press enter to continue.
==> vsphere-iso.linux-redhat-linux: Waiting 10s for boot...
==> vsphere-iso.linux-redhat-linux: HTTP server is working at http://10.151.182.165:8068/
==> vsphere-iso.linux-redhat-linux: Typing boot command...
==> vsphere-iso.linux-redhat-linux: Pausing after run of step 'boot_command: upe<down><down><end><wait>text inst.ks=http://10.151.182.165:8068/ks.cfg<enter><wait><leftCtrlOn>x<leftCtrlOff>'. Press enter to continue.
==> vsphere-iso.linux-redhat-linux: Pausing after run of step 'StepBootCommand'. Press enter to continue.
==> vsphere-iso.linux-redhat-linux: Waiting for IP...
==> vsphere-iso.linux-redhat-linux: IP address: 10.205.124.43
==> vsphere-iso.linux-redhat-linux: Pausing after run of step 'StepWaitForIp'. Press enter to continue.
```

> You can also toggle the common data source to "disk" to run out "http" as the issue.

I will try that (probably tomorrow)

**Comment by tenthirtyam** [comment] 2021-11-04 19:20
Let me know how it goes.

Ryan

**Comment by kinwolfqc** [comment] 2021-11-04 19:54
I had time for a last try before closing for the day, but I get an upload error with "disk" . Where is it trying to upload it exactly?
```

vsphere-iso.linux-redhat-linux: Uploading packer2086326018.iso to packer_cache/packer2086326018.iso
Build 'vsphere-iso.linux-redhat-linux' errored after 1 second 462 milliseconds: 500 Internal Server Error
```

**Comment by tenthirtyam** [comment] 2021-11-04 19:58
Is uploading to the datastore (`vsphere_datastore`)

Ryan

**Comment by kinwolfqc** [comment] 2021-11-05 12:02
The behaviour is the same with the "disk" option, it stops waiting after 2m30s

Here is the full debug log
https://gist.github.com/kinwolfqc/567445f99e74a164c6f8d9ea179167ca

**Comment by tenthirtyam** [comment] 2021-11-05 12:50
- Can you share what, if any, significant modifications have been made to the repository? 
- Does the same issue occur with Windows machine image builds, too?
- Is the Packer host running on-premises or in a virtual machine in your cloud instance?
- Do you have the ability to the same configuration against an on-premises instance to rule out configuration vs communication? 

Ryan

**Comment by kinwolfqc** [comment] 2021-11-05 13:10
- Code modif:  Not any modification really, but I only use the "builds" directory.  So I launch packer manually from the rhel7 folder and do not use the build.sh script

- I haven't tried a windows build so far with the cloud instance of vSphere, but the problem was there with our on-premises vSphere too, with both windows and linux built. I was building the templates with the `-debug` switch since then.  Thankfully, we did not update the images often in the last year.  I had even opened an issue in february, with packer 1.7.0,, but I opened it in the old(and wrong) repo:  https://github.com/jetbrains-infra/packer-builder-vsphere/issues/319  I finally have time to get back to this problem, especially since we are almost ready to integrate packer in our toolchain.

- Packer runs on my desktop right now, and since we are still working remote here, it goes through a vpn.   When it is integrated in our toolchain, it will run on the ansible controller that is on-premises. 

- The problem is also present with our on-premises vCenter.

**Comment by tenthirtyam** [comment] 2021-11-05 13:57
From the vSphere Client, are you able to confirm that that virtual machine is getting an IP address from DHCP? Once the machine image obtains an address and vCenter Server picks it up via VMTools it  should continue unless there is a communications issue back to the Packer host.

Ryan

**Comment by kinwolfqc** [comment] 2021-11-05 14:02
Yes, it does get an IP address.  I can only see it after the vmtools are installed, but it does get it.  That's also why it works if I control the flow of execution through the -debug flag, I make the script wait after the 'StepBootCommand' step and before the "Waiting for IP" step and only make it resume once I see the ip appearing in vCenter. (about 10 mins).

**Comment by kinwolfqc** [comment] 2021-11-05 15:05
I just ran the code, but from a server within(so, no VPN between packer and the vCenter) and the result was the same, packer destroyed the VM after 2m35s while the OS was still getting installed.

**Comment by tenthirtyam** [comment] 2021-11-05 15:18
Can you test with another guest OS (non-RHEL / non-RHEL derivative) to rule out the guest OS?

Ryan

**Comment by kinwolfqc** [comment] 2021-11-05 15:39
Windows 2019 gives the same kind of problem.  It fails after 2mXXs.  I ran the test on our on-premise vCenter this time.

**Comment by kinwolfqc** [comment] 2021-11-05 16:41
Is there a way to make it more verbose as to why it is failing after 2mins when the timeout is set at 20m(for RHEL) or 30m(for windows)

**Comment by kinwolfqc** [comment] 2021-11-19 00:21
Any update on this?  We are unable to use an automated pipeline to create the image right now.

**Comment by tenthirtyam** [comment] 2021-11-19 00:30
I've been unable to reproduce it with the environment information provided.

As a test, do you get the same issue if everything is on the same L2 network?

What OSI is the Packer host? Is it blocking inbound connections?

Ryan

**Comment by kinwolfqc** [comment] 2021-11-22 13:48
I ran the tests both from my workstation(windows 10, nothing blocked) and a linux host and both have the same problem.
I cannot run a test from the same subnet as the vCenter though(both in the cloud or on premises, the subnet for the vcenter is reserved and we cannot assign VM in it.)

**Comment by tenthirtyam** [comment] 2021-11-22 15:31
My apologies, @kinwolfqc,  I would need to defer further to one of the maintainers for next steps.

Perhaps @sylviamoss may have some recommendations for further troubleshooting.

Ryan

**Comment by kinwolfqc** [comment] 2021-12-07 16:16
Just making sure this issue doesn't close after X days of inactivity.  Still a problem for us.

**Comment by luciantuce** [comment] 2022-01-24 15:15
Hello guys! I am experiencing, I think pretty much the same thing with the initial description of the issue, using  packer version 1.7.9:

`Build 'vsphere-iso' errored after 3 minutes 31 seconds: Post "https://vcenter/sdk": EOF.`

The build machine from where the packer commands are being executed stays in a different DataCenter than the VCenter one (No FW Rules would be between them).

The awkward topic would be that in debug mode (command` packer build --debug file.json` ); it ends up with success (with template published to the vSphere).

Any ideas would be welcome!

**Comment by kinwolfqc** [comment] 2022-01-24 15:57
Still waiting for an answer here too.  We're building using debug mode for the moment, but it's such a pain that we're looking at alternative solutions.

**Comment by it-pappa** [comment] 2022-04-08 07:59
Hi, i can not get the same issue as you guys.  I dont know why its not working for you, but if you want - test my repo and see if that works better maby? 

https://github.com/it-pappa/Packer-vsphere/tree/main/RHEL8   (Also have for ubuntu and rocky). 
Packer example: 
`packer build -var-file=""auto.pkrvars.hcl .`

Tested on: 
Packer - 1.7.6
Packer - 1.7.8
Packer - 1.8.0
and works fine

**Comment by kinwolfqc** [comment] 2022-04-08 12:27
Hi @it-pappa , I got the same result(error) using your repo.  It stopped waiting for the IP after 2m43s (even though the setting is also set to 20mins in your code).  The VM was still downloading packages when it got shut down and removed.

I used packer 1.8.0

> packer build .
> vsphere-iso.rhel: output will be in this color.
> 
> ==> vsphere-iso.rhel: Creating VM...
> ==> vsphere-iso.rhel: Customizing hardware...
> ==> vsphere-iso.rhel: Mounting ISO images...
> ==> vsphere-iso.rhel: Adding configuration parameters...
> ==> vsphere-iso.rhel: Starting HTTP server on port 8460
> ==> vsphere-iso.rhel: Set boot order temporary...
> ==> vsphere-iso.rhel: Power on VM...
> ==> vsphere-iso.rhel: Waiting 5s for boot...
> ==> vsphere-iso.rhel: HTTP server is working at http://snip:8460/
> ==> vsphere-iso.rhel: Typing boot command...
> ==> vsphere-iso.rhel: Waiting for IP...
> ==> vsphere-iso.rhel: Clear boot order...
> ==> vsphere-iso.rhel: Power off VM...
> ==> vsphere-iso.rhel: Destroying VM...
> Build 'vsphere-iso.rhel' errored after 2 minutes 43 seconds: Post "https://snip/sdk": EOF
> 
> ==> Wait completed after 2 minutes 43 seconds
> 
> ==> Some builds didn't complete successfully and had errors:
> --> vsphere-iso.rhel: Post "https://snip/sdk": EOF
> 

If I restart it in -debug mode, I can control each steps and it works fine if I let the OS complete it's kickstart before allowing the "waiting for IP" step .

> packer build -debug .
> Debug mode enabled. Builds will not be parallelized.
> vsphere-iso.rhel: output will be in this color.
> 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepConnect'. Press enter to continue. 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepDownload'. Press enter to continue. 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepCreateCD'. Press enter to continue. 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepRemoteUpload'. Press enter to continue. 
> ==> vsphere-iso.rhel: Creating VM...
> 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepCreateVM'. Press enter to continue. ==> vsphere-iso.rhel: Customizing hardware...
> ==> vsphere-iso.rhel: Pausing after run of step 'StepConfigureHardware'. Press enter to continue. 
> ==> vsphere-iso.rhel: Mounting ISO images...
> ==> vsphere-iso.rhel: Pausing after run of step 'StepAddCDRom'. Press enter to continue. 
> ==> vsphere-iso.rhel: Adding configuration parameters...
> ==> vsphere-iso.rhel: Pausing after run of step 'StepConfigParams'. Press enter to continue. 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepCreateFloppy'. Press enter to continue. 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepAddFloppy'. Press enter to continue. 
> ==> vsphere-iso.rhel: Pausing after run of step 'StepHTTPIPDiscover'. Press enter to continue. 
> ==> vsphere-iso.rhel: Starting HTTP server on port 8465
> ==> vsphere-iso.rhel: Pausing after run of step 'StepHTTPServer'. Press enter to continue. 
> ==> vsphere-iso.rhel: Set boot order temporary...
> ==> vsphere-iso.rhel: Power on VM...
> ==> vsphere-iso.rhel: Pausing after run of step 'StepRun'. Press enter to continue. 
> ==> vsphere-iso.rhel: Waiting 5s for boot...
> ==> vsphere-iso.rhel: HTTP server is working at http://snip:8465/
> ==> vsphere-iso.rhel: Typing boot command...
> ==> vsphere-iso.rhel: Pausing after run of step 'boot_command: <esc><wait>vmlinuz initrd=initrd.img inst.geoloc=0 rd.driver.blacklist=dm-multipath net.ifnames=0 biosdevname=0 ks=http://snip:8465/kickstart.cfg<enter>'. Press enter to continue.
> ################## I WAIT HERE FOR THE OS(RHEL8) TO BE COMPLETELY INSTALLED BEFORE PRESSING ENTER #################
> ==> vsphere-iso.rhel: Waiting for IP...
> ==> vsphere-iso.rhel: IP address: snip
> ==> vsphere-iso.rhel: Pausing after run of step 'StepWaitForIp'. Press enter to continue. 
> ==> vsphere-iso.rhel: Using SSH communicator to connect: snip
> ==> vsphere-iso.rhel: Waiting for SSH to become available...
> ###ETC, it works fine from here and complete the template creation ##############

**Comment by it-pappa** [comment] 2022-04-08 18:22
@kinwolfqc  that is so weird! 
Is there a timeout some place. Do you have a special user for the vcenter that will get timed out or a firewall? 
2 mins and 43 seconds sound kina like an ALG (application Layered G(something)) in the firewall?

**Comment by reenberg** [comment] 2022-07-27 20:11
In my case it fails at the waiting for ip stage, after 1min and a few seconds, with the following `error []string{"POST \"/sdk\": 504 Gateway Time-out"}`.  This is due to a HAproxy instance being in front of the vSphere server, with a default timeout of 1minute for "hanging" connections.

So the previous comment seems plausible.

**Comment by tenthirtyam** [comment] 2022-12-12 04:31
@SylvainMartel (OP) - still seeing this issue?

**Comment by SylvainMartel** [comment] 2022-12-12 12:00
@tenthirtyam  I can't verify anymore since I do not work with, or have access to, a vmware cluster anymore.  New job all in the cloud now.

**Comment by tenthirtyam** [comment] 2022-12-12 13:27
Marking this issue as closed.

 If this issue is reproducible with the latest version of the plugin, please open a new issue linking back to this one for added context. Thank you!

**Closed by tenthirtyam** 2022-12-12 13:27 UTC
Labels: bug
