### ISSUE TITLE
Packer vsphere-iso not detecting change in IP address after reboot Ubuntu 21.10 auto install

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#127] opened 2021-11-08 10:26 UTC
_This issue was originally opened by @NathanDotTo in https://github.com/hashicorp/packer/issues/11385 and has been migrated to this repository. The original issue description is below._

---
#### Overview of the Issue

I appear to be seeing the same defect as in #8528.

I am auto installing Ubuntu 21.10 using Cloud Init. The initial boot gets an IP address, which is released, and then the second boot gets another IP address. Packer is stuck with the first IP address though.

==> vsphere-iso.dev_vm_server: Typing boot command...
==> vsphere-iso.dev_vm_server: Waiting for IP...
==> vsphere-iso.dev_vm_server: IP address: 10.122.244.252
==> vsphere-iso.dev_vm_server: Using SSH communicator to connect: 10.122.244.252
==> vsphere-iso.dev_vm_server: Waiting for SSH to become available...

But, the DHCP logs show that  10.122.244.252 was released, so the VM will get a different IP address after reboot.

Nov  5 09:39:13 xxx dhcpd: DHCPRELEASE of 10.122.244.252 from 00:50:56:89:57:1b (ubuntu-server) via ens192 (found) 

The logic here is that the initial boot of the VM is running a SSH server, but before the `ubuntu` user is configured via Cloud Init, so the attempt to connect to the SSH server at the initial IP address during that initial stage will fail authentication.

Then the server reboots and applies the Cloud Init settings. After rebooting, the IP address differs, so there is an I/O connection issue as Packer is trying the original address.

#### Reproduction Steps

```
source "vsphere-iso" "dev_vm_server" {
  username            = var.vcenter_username
  password            = var.vcenter_password
  vcenter_server      = var.vcenter_server
  cluster             = var.vcenter_cluster
  datacenter          = var.vcenter_datacenter
  datastore           = var.vcenter_vm_datastore
  guest_os_type       = "ubuntu64Guest"
  insecure_connection = "true"
  iso_checksum        = "sha256:e84f546dfc6743f24e8b1e15db9cc2d2c698ec57d9adfb852971772d1ce692d4"
  iso_urls            = ["https://releases.ubuntu.com/21.10/ubuntu-21.10-live-server-amd64.iso"]
  http_directory      = "./http"

  vm_name             = "dev_vm"
  CPUs                = 2
  RAM                 = 2048
  RAM_reserve_all     = true
  boot_wait           = "3s"
  convert_to_template = false
  boot_command        = [
    "c",
    "linux /casper/vmlinuz \"ds=nocloud-net;seedfrom=http://{{.HTTPIP}}:{{.HTTPPort}}/\" autoinstall quiet --- ",
    "<enter><wait>",
    "initrd /casper/initrd<enter><wait>",
    "boot<enter>",
  ]
  network_adapters {
    network      = "xxx"
    network_card = "e1000"
    mac_address = "00:50:56:89:57:1b"
  }
  storage {
    disk_size             = 40960
    disk_thin_provisioned = true
  }

  ssh_username = "ubuntu"
  ssh_password = "ubuntu"
  ssh_timeout  = "60m"
  ssh_handshake_attempts = 60
}

build {
  sources = [
    "source.vsphere-iso.dev_vm_server"
  ]

...
}


Steps to reproduce this issue

### Packer version

1.7.8

### Simplified Packer Template

See above

### Operating system and Environment details

macOS 12.0.1

### Log Fragments and crash.log files

https://gist.github.com/NathanDotTo/cff4ce63cce2bb66230e3c7740aab09e

**Comment by NathanDotTo** [comment] 2021-11-08 12:21
Hi, see user-data below:

#cloud-config
autoinstall:
  version: 1
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
    - arches: [amd64, i386]
      uri: http://gb.archive.ubuntu.com/ubuntu
    - arches: [default]
      uri: http://ports.ubuntu.com/ubuntu-ports
  users:
  - default
  - name: ubuntu
    lock_passwd: false
    passwd: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
  write_files:
  - path: /etc/ssh/sshd_config
    content: |
         Port 22
         Protocol 2
         HostKey /etc/ssh/ssh_host_rsa_key
         HostKey /etc/ssh/ssh_host_dsa_key
         HostKey /etc/ssh/ssh_host_ecdsa_key
         HostKey /etc/ssh/ssh_host_ed25519_key
         UsePrivilegeSeparation yes
         KeyRegenerationInterval 3600
         ServerKeyBits 1024
         SyslogFacility AUTH
         LogLevel INFO
         LoginGraceTime 120
         PermitRootLogin yes
         StrictModes no
         RSAAuthentication yes
         PubkeyAuthentication no
         IgnoreRhosts yes
         RhostsRSAAuthentication no
         HostbasedAuthentication no
         PermitEmptyPasswords no
         ChallengeResponseAuthentication no
         X11Forwarding yes
         X11DisplayOffset 10
         PrintMotd no
         PrintLastLog yes
         TCPKeepAlive yes
         AcceptEnv LANG LC_*
         Subsystem sftp /usr/lib/openssh/sftp-server
         UsePAM yes
         AllowUsers ubuntu
  identity:
    hostname: coolsox-fso-dev-vm
    username: ubuntu
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
  network:
    network:
      version: 2
      ethernets:
        ens32:
          dhcp4: true
          dhcp-identifier: mac
  ssh:
    allow-pw: true
    install-server: true
  user-data:
    disable_root: false
  locale: en_US
  keyboard:
    layout: en
  storage:
    layout:
      name: direct
    config:
      - type: disk
        id: disk0
        match:
          size: largest
      - type: partition
        id: boot-partition
        device: disk0
        size: 500M
      - type: partition
        id: root-partition
        device: disk0
        size: -1
  late-commands:
    - 'sed -i "s/dhcp4: true/&\n      dhcp-identifier: mac/" /target/etc/netplan/00-installer-config.yaml'
    - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu

**Comment by tenthirtyam** [comment] 2021-11-08 12:28
Have you tried using ens33 (not ens32) with e1000, or more preferably ens192 with vmxnet3?

Ryan

**Comment by tenthirtyam** [comment] 2021-11-08 12:34
Note, you can always use

**Comment by tenthirtyam** [comment] 2021-11-08 12:37
Take a look at the Ubuntu 2@.04 example from my repo: https://github.com/rainpole/packer-vsphere. I don't specify the network type and let it determine based on the nic type of vmxnet3. Works perfectly.

Ryan

**Comment by NathanDotTo** [comment] 2021-11-10 11:19
Many thanks for the help here Ryan.

I changed the network card to vmxnet3. That changed the interface to ens160, so I also changed my original user-data network section to update that interface, but that did not work.

Then I added a user-data packages section to install open-vm-tools. That did install the VM tools, but did not change the behaviour.

Finally I removed the user-data network section, and the late command that sed’ed the network config. That worked. Importantly, the DHCP IP address was the same after reboot.

My original approach was inspired by:

https://nickcharlton.net/posts/automating-ubuntu-2004-installs-with-packer.html

Which turns out not to work as expected.

Now I have user-data:

#cloud-config
autoinstall:
  version: 1
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
    - arches: [amd64, i386]
      uri: http://gb.archive.ubuntu.com/ubuntu
    - arches: [default]
      uri: http://ports.ubuntu.com/ubuntu-ports
  users:
  - default
  - name: ubuntu
    lock_passwd: false
    passwd: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
  write_files:
  - path: /etc/ssh/sshd_config
    content: |
         Port 22
         Protocol 2
         HostKey /etc/ssh/ssh_host_rsa_key
         HostKey /etc/ssh/ssh_host_dsa_key
         HostKey /etc/ssh/ssh_host_ecdsa_key
         HostKey /etc/ssh/ssh_host_ed25519_key
         UsePrivilegeSeparation yes
         KeyRegenerationInterval 3600
         ServerKeyBits 1024
         SyslogFacility AUTH
         LogLevel INFO
         LoginGraceTime 120
         PermitRootLogin yes
         StrictModes no
         RSAAuthentication yes
         PubkeyAuthentication no
         IgnoreRhosts yes
         RhostsRSAAuthentication no
         HostbasedAuthentication no
         PermitEmptyPasswords no
         ChallengeResponseAuthentication no
         X11Forwarding yes
         X11DisplayOffset 10
         PrintMotd no
         PrintLastLog yes
         TCPKeepAlive yes
         AcceptEnv LANG LC_*
         Subsystem sftp /usr/lib/openssh/sftp-server
         UsePAM yes
         AllowUsers ubuntu
  identity:
    hostname: dev-vm
    username: ubuntu
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
  ssh:
    allow-pw: true
    install-server: true
  user-data:
    disable_root: false
  locale: en_US
  keyboard:
    layout: en
  storage:
    layout:
      name: direct
    config:
      - type: disk
        id: disk0
        match:
          size: largest
      - type: partition
        id: boot-partition
        device: disk0
        size: 500M
      - type: partition
        id: root-partition
        device: disk0
        size: -1
  packages:
    - openssh-server
    - open-vm-tools
    - cloud-init
  late-commands:
    - echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ubuntu

The Packer HCL is the same as previously, with the change to the network card type, and without the fixed MAC address (which I was using for DHCP debug purposes).

Regards

Nathan

**Comment by tenthirtyam** [comment] 2021-11-10 11:40
Glad to hear it's working now!

Please be sure to close the issue once all is confirmed as good.

Ryan

**Comment by NathanDotTo** [comment] 2021-11-10 12:06
I can't close this issue as I don't see a "Close Issue" button. Please feel free to close on my behalf.

**Comment by tenthirtyam** [comment] 2021-11-10 12:28
@hc-github-team-packer, please close.

Ryan

**Comment by nywilken** [comment] 2021-11-11 22:07
Thanks for working through this issue @tenthirtyam. Closing as requested.

**Closed by nywilken** 2021-11-11 22:07 UTC

**Comment by tenthirtyam** [comment] 2021-11-11 22:14
Happy to help!
