### ISSUE TITLE
`vsphere-template`: VM at path `/MyDataCenter/vm/Discovered virtual machine/ubuntu` not found

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/packer-plugin-vsphere#224] opened 2022-10-13 14:57 UTC
#### Overview of the Issue

I am trying to place the VM template under a Datacenter folder 

`convert_to_template = true` places the VM template into path ` /MyDataCenter/templates/`

But I'm getting this error

`(vsphere-template): VM at path /MyDataCenter/vm/Discovered virtual machine/ubuntu not found`

```hcl
source "vsphere-iso" "my_ubuntu" {
  # ...
}

build {
  name    = "my_ubuntu"
  sources = ["source.vsphere-iso.my_ubuntu"]

  post-processors {
    # Create VM template
    post-processor "vsphere-template" {
      host       = var.vcenter_server
      username   = var.vsphere_username
      password   = var.vsphere_password
      insecure   = var.vsphere_insecure_connection
      datacenter = var.vsphere_datacenter
      folder     = "/templates/"
    }
  }
}
```

### Packer Version

Please provide the Packer version.

### Plugin Version and Builders

Please provide the plugin version.

Please select the builder.

- [x] `vsphere-iso`
- [ ] `vsphere-clone`

### VMware vSphere Version

`7.0.3.00700`

### Guest Operating System

- Ubuntu 22.04: `ubuntu-22.04.1-live-server-amd64.iso`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log or use the [GitHub detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

### Operating System and Environment Details

WSL2

**Comment by tenthirtyam** [comment] 2022-12-11 21:33
Research:

Based on the errors it's failing on this function and throwing the error in L152.:

https://github.com/hashicorp/packer-plugin-vsphere/blob/a0992c7396605b33492e7b9447569110e1bb7033/post-processor/vsphere-template/step_mark_as_template.go#L142-L161

As the expected `remoteFolder` is hard set in L26 of the post-processor:

https://github.com/hashicorp/packer-plugin-vsphere/blob/a0992c7396605b33492e7b9447569110e1bb7033/post-processor/vsphere-template/step_mark_as_template.go#L25-L27

**Comment by razethion** [comment] 2023-02-21 21:54
Re-bumping this thread. 

> Can you confirm if `/MyDataCenter/vm/Discovered virtual machine/` exists and has not been removed

This is irrelevant because the code will always expect the VM to exist in that folder. If "folder" is left blank in vsphere-iso, it fails because the VM is created in the root of the datacenter. That sections should not assume it's in that folder unless explicitly specified.

**Comment by tenthirtyam** [comment] 2023-02-21 21:57
> See #249.

That's a duplicate of this one.

**Comment by razethion** [comment] 2023-02-21 22:00
> That's a duplicate of this one.

Regardless, it needs to be addressed as it is undocumented unexpected behavior. See my suggestion from above.


> Packer should not assume it's in that folder unless explicitly specified, because vsphere-iso implies it is optional.

**Comment by EtienneBruines** [comment] 2023-05-23 10:56
> Can you confirm if `/MyDataCenter/vm/Discovered virtual machine/` exists and has not been removed? Though, I'm not sure what the reasoning behind expecting this folder to exist. Typically, it's only used to place VMs when hosts are imported into a cluster with existing VMs.

This directory never even existed with me, since I defined a `folder` in `source "vsphere-iso" "my_ubuntu"`, but for some reason the post processing expects it to be in that `Discovered virtual machine` folder.

**Comment by tenthirtyam** [comment] 2023-05-23 12:08
> This directory never even existed with me, since I defined a `folder` in `source "vsphere-iso" "my_ubuntu"`, but for some reason the post processing expects it to be in that `Discovered virtual machine` folder.

Unfortunately the expected `remoteFolder` is hard set in L26 of the post-processor and needs to be evaluated for a more robust approach.

https://github.com/hashicorp/packer-plugin-vsphere/blob/a0992c7396605b33492e7b9447569110e1bb7033/post-processor/vsphere-template/step_mark_as_template.go#L25-L27

**Comment by EtienneBruines** [comment] 2023-05-23 12:10
Is it meant to be overwritten here and for some reason it doesn't? Or should it have been set dynamically from the start?

https://github.com/hashicorp/packer-plugin-vsphere/blob/a0992c7396605b33492e7b9447569110e1bb7033/post-processor/vsphere-template/step_mark_as_template.go#L29-L33

**Closed** 2023-10-19 21:06 UTC
Labels: bug, post-processor/vsphere-template
