### ISSUE TITLE
Build fails when there are no additional configuration parameters to process

### ISSUE THREAD

**Issue by jhennessey** [hashicorp/packer-plugin-vsphere#482] opened 2024-10-17 20:04 UTC
#### Overview of the Issue

Build fails when there are no additional configuration parameters to process

This PR seemingly caused the issue: #468 
This line would appear to be the culprit: https://github.com/hashicorp/packer-plugin-vsphere/commit/5e944bc027af0a1120ec81a9643c5f90e3f5341b#diff-f81447593c9b389c1718a91e14307807b280b36f7c76f64a150637d6faba312bR1340

#### Reproduction Steps

Attempt to build using the `vsphere-clone` builder with none of the optional configuration options. This will result in a failure (see message below)

### Packer Version

- 1.10.1

### Plugin Version and Builders

- 1.4.1

Please select the builder.

- [] `vsphere-iso`
- [x] `vsphere-clone`

### VMware vSphere Version

- 7.0.3

### Guest Operating System

- Windows Server 2022 21H2

### Simplified Packer Buildfile

```
source "vsphere-clone" "test-agent" {
  vcenter_server          = "${var.vcenter_server}"
  username                = "${var.vsphere_username}"
  password                = "${var.vsphere_password}"
  datacenter              = "${var.vsphere_datacenter}"
  cluster                 = "${var.vsphere_cluster}"
  datastore               = "${var.vsphere_datastore}"
  folder                  = "${var.vsphere_folder}"
  template                = "${var.vsphere_template}"
  
  vm_name                 = "${var.vm_name_prefix}:provisioning"
  create_snapshot         = true
  linked_clone            = false
  NestedHV                = true

  communicator            = "ssh"
  ssh_username            = "${var.admin_username}"
  ssh_password            = "${var.admin_password}"
}

build {
  sources = [
    "source.vsphere-clone.test-agent"
    ]
...
```

### Operating System and Environment Details

Please add any information you can provide about the environment.

- Running packer using the hashicorp/packer image: [link](https://hub.docker.com/layers/hashicorp/packer/1.10.1/images/sha256-14f191c3469f8ee421e22b612265b5553736564fe67dab3d16628b1d7378d62b?context=explore)

### Log Fragments and `crash.log` Files

```
error adding configuration parameters: no changes to apply
Step "StepConfigParams" failed, aborting...
```

**Comment by tenthirtyam** [comment] 2024-10-17 20:30
Looking into it - related to #468.

@lbajolet-hashicorp 0 we might need to revert this change and issue a v1.4.2 and take it up again.

**Comment by tenthirtyam** [comment] 2024-10-17 20:47
Duplicate of #481

**Closed by tenthirtyam** 2024-10-17 20:47 UTC
Labels: bug

**Comment by tenthirtyam** [comment] 2024-10-17 20:53
Pushing out v1.4.2 shortly.

**Comment by tenthirtyam** [comment] 2024-10-17 21:29
> [!IMPORTANT]  
>
> **COMMUNITY NOTE**
>
> Patch release v1.4.2 is now available.
>
> Ryan and Lucas
