### ISSUE TITLE
vsphere-iso remove_cdrom leaves iso files in packer cache

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#162] opened 2022-01-24 11:35 UTC
_This issue was originally opened by @myllynen in https://github.com/hashicorp/packer/issues/11515 and has been migrated to this repository. The original issue description is below._

---
#### Overview of the Issue

Using vsphere-iso builder with

```
      "cd_files": ["inst.cfg"],
      "cd_label": "inst.cfg",
      "remove_cdrom": true,
```

works and the CD-ROM is removed from the VM/template as expected but the ISO file is left behind in packer_cache directory at vSphere.

#### Reproduction Steps

1. Build VM/template using vsphere-iso builder using the above configuration options
1. Observe how the ISO file is littering packer_cache after a successful run

### Packer version

1.7.8

**Comment by myllynen** [comment] 2022-01-24 12:14
Thanks for migrating the ticker, I failed to see that this repo and used the main packer repo instead.

This looks like a dupe of https://github.com/hashicorp/packer-plugin-vsphere/issues/50.

Thanks.

**Comment by tenthirtyam** [comment] 2022-01-24 13:01
Duplicate of #14.

cc @hc-github-team-packer @azr

**Comment by nywilken** [comment] 2022-01-24 14:48
Thanks @myllynen and @tenthirtyam. I'll close this in favor of #14.

**Closed by nywilken** 2022-01-24 14:48 UTC
