### ISSUE TITLE
vsphere-iso requires that iso_paths datastore is the same as the VM datastore

### ISSUE THREAD

**Issue by tgavent** [hashicorp/packer-plugin-vsphere#105] opened 2021-09-08 18:29 UTC
Currently I am trying to create a VM on one datastore and mount that VM with an ISO located in another datastore. 

This is a continuation of this [issue](https://github.com/jetbrains-infra/packer-builder-vsphere/issues/322). I was told this is the correct place to forward this issue. 

Taken from the aforementioned issue:

> In a similar exercise with Terraform, I am creating a VM where the VM datastore and the ISOs datastore are distinct, for the sake of tidiness if nothing else.
> 
> In the Terraform case, this separation of datastores is fine.
> 
> In the Packer case, it is not, but it should be.
> 
>> @rushi47 I know this is probably old but I ran into this same exact issue and what fixed it was that in your variables, you specified this
>> 
>> "vcenter_datastore": "ESX07-LOCAL-DS01"
> >
> >But in your iso_paths, you specified a different datastore location:
>> 
>> "iso_paths": [
>>          "[ESX01-LOCAL-DS01] /ISO/CentOS-7-x86_64-Minimal-1511.iso"
>> Change the iso_path and vcenter_datastore to match and you should be good.
> 
> This is the correct answer here, but this is also wrong. There is no reason to assume that the ISO files should be in the same datastore as the VM. It should be possible to have distinct datastores.

The error I receive is `error mounting image: Invalid configuration for device '0'`. Note that we do not have this error when the VM is in the same datastore as the ISO file.

Unfortunately, this bug has not been reproducible. It works most of the time, but fails on rare occasions.

**Comment by tenthirtyam** [comment] 2021-09-08 19:36
Can you update the issue with Packer version and Plugin for vSphere version? Those are requested in the issue template. It would be helpful for those that may triage.

For example:

```
packer {
  required_version = ">= 1.7.4"
  required_plugins {
    vsphere = {
      version = ">= v1.0.1"
      source  = "github.com/hashicorp/vsphere"
    }
  }
}
```

Of the countless builds that I've performed with `vsphere-iso`, I've never encountered this issue. Typically my `iso_datastore` is an NFS-backed datastore, the `datastore` for the plug-in is vSAN, and the backing datastore for a content library is NFS.

My examples can be seen [here](https://github.com/rainpole/packer-vsphere).

Ryan

Ryan

**Comment by gaima8** [comment] 2021-09-21 14:37
I have this problem using packer 1.7.5 and v1.0.1 of the vsphere plugin.
It fails every time for me.

**Comment by gaima8** [comment] 2021-09-22 15:21
> I have this problem using packer 1.7.5 and v1.0.1 of the vsphere plugin.
> It fails every time for me.

Never mind, despite vSphere saying it was fine the NFS datastore wasn't.
I don't have this problem.

**Comment by tenthirtyam** [comment] 2021-12-03 15:56
@tgavent - are you still observing this issue using the `vsphere-iso` builder?

Ryan

**Comment by tenthirtyam** [comment] 2022-05-06 12:12
This issue has not been reproducible as mentioned prior in the thread.

Due to no response in 5 months I recommend issue closure.

cc @nywilken @azr 

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by nywilken** [comment] 2022-07-25 20:04
Closing since there have been no updates to the issue. If you believe this is still an issue please open a new bug issue with the information requested in the template.

**Closed by nywilken** 2022-07-25 20:04 UTC
