### ISSUE TITLE
Packer image with EFI firmware reverts to BIOS firmware when deploying from a content library.

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#122] opened 2021-10-19 18:06 UTC
_This issue was originally opened by @mrdanielmartins in https://github.com/hashicorp/packer/issues/11343 and has been migrated to this repository. The original issue description is below._

---
Pardon me if I have ended up at the wrong place.

#### Overview of the Issue

I have several Packer images. These range from Linux to Windows. All set with the firmware of EFI. I recently tried utilising Packer to clone/import to a content library. The import as works intended and all appear as OVF templates in the content library. 

However, when deploying a new VM of the OVF template from the content library, all VMs revert to BIOS firmware. Of course, this now means machines fail to boot as they are EFI built. This occurs whether I use Packer to upload to the content library or manually do it myself from the Packer template. 

I have tried creating a manual template. Then cloned it to the content library for use as an OVA template. I do not get the same issue as above. All VMs deployed from the content library stay consistent in EFI firmware.

I have seen several posts, but there seems to be no guidance on how one solves this? Could I get your assistance, please?  

#### Reproduction Steps

Packer template image. Packer upload to the content library. Deploy manually from the OVA in the content library. The virtual machine will revert to BIOS firmware, thus breaking boot. 

### Versions

Packer 1.7.6
Packer-Plugin-vSphere 1.0.1

### Simplified Packer Template

Pardon the single file. It contains the variables, kickstart, source and builder:
https://gist.github.com/mrdanielmartins/4a9eb3771d489cd74797ed95f7a8f15c

### Operating system and Environment details

Gitlab-runner: CentOS 7.9
OS images: AlmaLinux 8.4 and Windows 10, 2016 and 2019.
Environment: VMware Center 6.7U3

### Log Fragments and crash.log files

Packer log: https://gist.github.com/mrdanielmartins/e7fe15025450f70432bb6a24601c3aad

**Comment by tenthirtyam** [comment] 2021-10-20 02:14
There was an issue with the content library pre-vSphere 7.0 Update 2 where efi / efi-secure based images in OVF format saved to the content library (create in any manner) would revert to BIOS during the cloning.

You can see my notes in one of my old commits here: https://github.com/rainpole/packer-vsphere/commit/70199b6fab0120c051b9ead182dacdd6e90de839#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L227

Ryan

**Comment by mrdanielmartins** [comment] 2021-10-20 13:45
@tenthirtyam 

Many thanks for the comment. 👍

Luckily I do not get the same with manual templates and clones to the content library. These work all fine and persist with the EFI firmware configured when deployed from the content library.

My issue applies only to Packer based templates. Whether or not I push to the content library manually or via Packer.
So seems to be more of Packer rather than vSphere? 

Daniel

**Comment by tenthirtyam** [comment] 2021-10-20 20:21
I can confirm that this is not an issue with the packer (1.7.5+), the vsphere-iso plugin (1.0.1+), and vSphere 7.0 U2+.

In my project - github.com/rainpole/packer-vsphere all images are create as `efi-secure` (`efi` for Rocky) and have no issues with being deployed from the content library from the OVF template form.

Ryan

**Comment by mrdanielmartins** [comment] 2021-10-20 23:11
> I can confirm that this is not an issue with the Packer `1.7.5+`, the `vsphere-iso` plugin `1.0.1+`, and vSphere 7.0 U2+.
> 
> In my project - [github.com/rainpole/packer-vsphere](https://github.com/rainpole/packer-vsphere) all images are create as `efi-secure` (`efi` for Rocky) and have no issues with being deployed from the content library from the OVF template form.
> 
> Without going into too much detail, there was an issue in earlier at least vSphere 7.0.0 and 7.0.1 where when a VM was deployed using OVF.
> 
> Ryan

Ryan, while it is lovely to read that it works in your `vSphere 7.0 U2+` environment, I can't say the same for my experience. 

I am running vSphere version `6.7 U3`, which consists of: 
- `Linux vCenter Server Appliance 6.7U3`
- `ESXi 6.7U3` 

If what you are getting at is the resetting of the firmware only occurs to vSphere environments before version `7.0.2`, it would be great to have confirmation by those who develop Packer and or its plugins. Maybe even an article from VMware any exists?

Like that, others with the same issue aren't looking for a needle in a haystack. Of course, some won't have the option of shifting their vSphere environments to a later version. 

Dan

**Comment by tenthirtyam** [comment] 2021-10-20 23:37
I've sent an inquiry to our engineer who resolved the issue in 7.0 U3 if it also exists in 6.7 U3.

Ryan

**Comment by tenthirtyam** [comment] 2022-02-17 07:21
This should be resolved once you are able to upgrade to vSphere 7.0.2 or later.

**Comment by tenthirtyam** [comment] 2022-04-07 12:57
@mrdanielmartins - You can reference Bug 2639957 with VMware GSS if needed.

**Summary**: _When an OVF with the firmware of `efi` is deployed from the content library, it results in a new virtual machine with firmware `bios` instead of `efi`. A regression was committed resulting in the `efiSecureBootEnabled` being overwritten while updating BIOS setting in the VMConfiguraiton Spec. This was becasue in case an OVF has `firmware=efi`, the `vmSpec.getBios()` would always be `null`. A fix was issued in 7.0 U2 to ensure that VMConfiguraiton Spec would hold the specified firmware value._

@hc-github-team-packer, @azr, @nywilken - this would not be a Packer plugin for vSphere bug.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by nywilken** [comment] 2022-04-08 21:37
Thank @tenthirtyam we really appreciate the help. I’m going to close the issue and pin it for now.

**Closed by nywilken** 2022-04-08 21:37 UTC
Labels: upstream-bug
