### ISSUE TITLE
Why customize parameter configure only for linux 

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#165] opened 2022-01-28 14:51 UTC
_This issue was originally opened by @R-G-11 in https://github.com/hashicorp/packer/issues/11535 and has been migrated to this repository. The original issue description is below._

---
I want to change IP of Windows template running on VMware env without DHCP server.
I'M using vsphere-clone builder and while I'm using customize paramter withouht linux _info it tells me that the paramter is empty
I saw that there was a issue that closed withou answer
https://github.com/hashicorp/packer/issues/10041#issue-714607069
I'd like to help with that issue please

**Comment by tenthirtyam** [comment] 2022-08-20 04:19
Duplicate of #7.

cc @nywilken 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-09-28 03:19
Duplicate of #7 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment] 2022-09-28 03:20
Duplicate of #7

**Closed** 2022-09-28 03:21 UTC
Labels: duplicate, question
