### ISSUE TITLE
[vsphere-clone] How to use vm template in content library as source vm

### ISSUE THREAD

**Issue by huonguyenlt** [hashicorp/packer-plugin-vsphere#137] opened 2021-11-29 15:08 UTC
I want to create vm from vm template which is in the content library. How do I provide full path of the vm template to the "template" in the clone configuration?

**Comment by iamjoos** [comment] 2022-09-13 15:27
It doesn't seem to be supported yet, please see #43.

**Comment by tenthirtyam** [comment] 2022-09-13 15:32
Existing enhancement.

Duplicate of #43.

cc @nywilken

**Comment by tenthirtyam** [comment] 2022-10-04 03:38
Duplicate of #43

**Closed by tenthirtyam** 2022-10-04 03:38 UTC
Labels: duplicate, question
