### ISSUE TITLE
[vsphere-iso] Floppy upload to datastore results in broken pipe or 404 error

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vsphere#172] opened 2022-03-17 00:06 UTC
_This issue was originally opened by @tech-priv in https://github.com/hashicorp/packer/issues/11655 and has been migrated to this repository. The original issue description is below._

---
Dear packer experts,

I'm struggling to upload a floppy image (same goes with cd_rom image) from Packer using the vsphere-iso plugin.
I was able to deploy a Linux ISO file located in a datacenter within vCenter and it works well. 
As soon as I have some provisioning using floppy of cdrom images that needs to be uploaded to the datastore, it fails. 

Manually uploading the files from the vSphere Client which should mean vCenter privileges are just fine.  

Please excuse any information I could have missed that would be required to troubleshoot

Any idea or help is very welcomed. 

Thank you !

#### Overview of the Issue

vCenter version 6.7
Using vshere-iso builder to deploy an ISO file available in the ESXi datastore, provisioning it with a floppy image for the OS installation.
Datastore ISO is correctly detected and mounted but the build fails everytime during floppy image upload.

#### Reproduction Steps

Run following command using the builder below:

packer build -debug -var 'username=xxx' -var 'password=yyyy' .

Randomly, one build outputs a **404 Not found** error and one build outputs a **write tcp 10.1.21.208:57236->10.1.11.230:443: write: broken pipe**

In every case, the HTTP request that seems to fail is:
Put "https://<host>/folder/<vm-name-folder>/packer-tmp-created-floppy.flp?dcPath=<datacenter>&dsName=<datastore>

### Packer version

1.8.0

### Simplified Packer Template

[packer-template.pkr.hcl](https://gist.github.com/tech-priv/19cf53464046cb7c370bb787afc5b8d8#file-packer-vsphere-iso-broken-pipe-pkr-hcl) 

### Operating system and Environment details

Ubuntu 20.04.4 LTS
PACKER_LOG=1  

### Log Fragments and crash.log files

[packer-broken-pipe-error.log](https://gist.github.com/tech-priv/19cf53464046cb7c370bb787afc5b8d8#file-packer-broken-pipe-log) 
[packer-404-not-found.log](https://gist.github.com/tech-priv/19cf53464046cb7c370bb787afc5b8d8#file-packer-404-error-log)

**Comment by it-pappa** [comment] 2022-04-08 07:49
Hi, i guess you will use the config file for ubuntu. use CD option:
cd_files = [
"./vms/ubuntu/http/meta-data",
"./vms/ubuntu/http/user-data"]

Example: https://github.com/it-pappa/Packer-vsphere/blob/main/Ubuntu.20.04/builder.pkr.hcl

**Comment by tech-priv** [comment] 2022-05-05 13:25
Hi @it-pappa and thank you for your answer. 

Ubuntu is my environment OS where I'm runnign packer. The destination OS that I'm trying to deploy on vSphere is either RHEL6 or Windows. 
* For RHEL6, it seems like I can simply use a "boot_command" for RHEL and copy a cfg file
* For Windows, I need to upload an autounattend file either in floppy or cdrom which results in the 404 error / broken pipe.

**Comment by it-pappa** [comment] 2022-05-07 16:37
@tech-priv  i know there is some windows packer builds up there in github. But i didnt bother. Took me longer to make it with packer then to actually install it and just run an ansible job to patch it etc.

**Comment by tenthirtyam** [comment] 2022-05-07 17:08
[vmware-samples/packer-examples-for-vsphere](https://github.com/vmware-samples/packer-examples-for-vsphere)

**Comment by it-pappa** [comment] 2022-05-10 06:22
@tenthirtyam that windows example i cant wait to try :)

**Comment by tenthirtyam** [comment] 2022-07-29 01:13
Duplicate of #21.

cc @nywilken

**Comment by tenthirtyam** [comment] 2022-07-29 17:09
Resolved per https://github.com/hashicorp/packer-plugin-vsphere/issues/21#issuecomment-1199762745

cc @nywilken 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by nywilken** [comment] 2022-07-29 19:47
Closing as requested.

**Closed by nywilken** 2022-07-29 19:47 UTC
